/*
 * open_eagle.c
 * tests_file: open_eagle_tests.c
 *
 * Open an eagle snapshot and loading its general info (header, constants, etc)
 *
 * @param: fpath: File path
 * @param: eagle: An eagle object to be filled
 *
 * @return: File indicator (or in case of error standard EXIT_FAILURE)
 */


#include <stdio.h>
#include <stdlib.h>
#include <High5/High5.h>
#include <assert.h>
#include "./open_eagle.h"


#ifndef PRINT
#define PRINT printf
#endif


hid_t open_eagle(char *fpath, eagle_t *eagle)
{
  hid_t file_id; /*File and group identifiers*/

  file_id = open_h5(fpath, H5F_ACC_RDONLY, H5P_DEFAULT);

  read_h5attrs(
    file_id, "Header",
    "BoxSize", H5T_NATIVE_DOUBLE, &(eagle->header.BoxSize),
    "E(z)", H5T_NATIVE_DOUBLE, &(eagle->header.E_z),
    "ExpansionFactor", H5T_NATIVE_DOUBLE, &(eagle->header.ExpansionFactor),
    "H(z)", H5T_NATIVE_DOUBLE, &(eagle->header.H_z),
    "HubbleParam", H5T_NATIVE_DOUBLE, &(eagle->header.HubbleParam),
    "Omega0", H5T_NATIVE_DOUBLE, &(eagle->header.Omega0),
    "OmegaBaryon", H5T_NATIVE_DOUBLE, &(eagle->header.OmegaBaryon),
    "OmegaLambda", H5T_NATIVE_DOUBLE, &(eagle->header.OmegaLambda),
    "Redshift", H5T_NATIVE_DOUBLE, &(eagle->header.Redshift),
    "Time", H5T_NATIVE_DOUBLE, &(eagle->header.Time),
    "MassTable", H5T_NATIVE_DOUBLE, eagle->header.MassTable,
    "Flag_Cooling", H5T_NATIVE_INT, &(eagle->header.Flag_Cooling),
    "Flag_DoublePrecision", H5T_NATIVE_INT, &(eagle->header.Flag_DoublePrecision),
    "Flag_Feedback", H5T_NATIVE_INT, &(eagle->header.Flag_Feedback),
    "Flag_IC_Info", H5T_NATIVE_INT, &(eagle->header.Flag_IC_Info),
    "Flag_Metals", H5T_NATIVE_INT, &(eagle->header.Flag_Metals),
    "Flag_Sfr", H5T_NATIVE_INT, &(eagle->header.Flag_Sfr),
    "Flag_StellarAge", H5T_NATIVE_INT, &(eagle->header.Flag_StellarAge),
    "NumFilesPerSnapshot", H5T_NATIVE_INT, &(eagle->header.NumFilesPerSnapshot),
    "NumPart_ThisFile", H5T_NATIVE_INT, &(eagle->header.NumPart_ThisFile),
    "NumPart_Total", H5T_NATIVE_UINT, &(eagle->header.NumPart_Total),
    "NumPart_Total_HighWord", H5T_NATIVE_UINT, &(eagle->header.NumPart_Total_HighWord),
    "RunLabel", H5T_STRING, eagle->header.RunLabel,
    NULL
  );

  read_h5attrs(
    file_id, "Units",
    "UnitDensity_in_cgs", H5T_NATIVE_DOUBLE, &(eagle->units.UnitDensity_in_cgs),
    "UnitEnergy_in_cgs", H5T_NATIVE_DOUBLE, &(eagle->units.UnitEnergy_in_cgs),
    "UnitLength_in_cm", H5T_NATIVE_DOUBLE, &(eagle->units.UnitLength_in_cm),
    "UnitMass_in_g", H5T_NATIVE_DOUBLE, &(eagle->units.UnitMass_in_g),
    "UnitPressure_in_cgs", H5T_NATIVE_DOUBLE, &(eagle->units.UnitPressure_in_cgs),
    "UnitTime_in_s", H5T_NATIVE_DOUBLE, &(eagle->units.UnitTime_in_s),
    "UnitVelocity_in_cm_per_s", H5T_NATIVE_DOUBLE, &(eagle->units.UnitVelocity_in_cm_per_s),
    NULL
  );

  read_h5attrs(
    file_id, "Constants",
    "AVOGADRO", H5T_NATIVE_DOUBLE, &(eagle->constants.AVOGADRO),
    "BOLTZMANN", H5T_NATIVE_DOUBLE, &(eagle->constants.BOLTZMANN),
    "C", H5T_NATIVE_DOUBLE, &(eagle->constants.C),
    "CM_PER_MPC", H5T_NATIVE_DOUBLE, &(eagle->constants.CM_PER_MPC),
    "ELECTRONCHARGE", H5T_NATIVE_DOUBLE, &(eagle->constants.ELECTRONCHARGE),
    "ELECTRONMASS", H5T_NATIVE_DOUBLE, &(eagle->constants.ELECTRONMASS),
    "EV_TO_ERG", H5T_NATIVE_DOUBLE, &(eagle->constants.EV_TO_ERG),
    "GAMMA", H5T_NATIVE_DOUBLE, &(eagle->constants.GAMMA),
    "GAS_CONST", H5T_NATIVE_DOUBLE, &(eagle->constants.GAS_CONST),
    "GRAVITY", H5T_NATIVE_DOUBLE, &(eagle->constants.GRAVITY),
    "HUBBLE", H5T_NATIVE_DOUBLE, &(eagle->constants.HUBBLE),
    "PI", H5T_NATIVE_DOUBLE, &(eagle->constants.PI),
    "PLANCK", H5T_NATIVE_DOUBLE, &(eagle->constants.PLANCK),
    "PROTONMASS", H5T_NATIVE_DOUBLE, &(eagle->constants.PROTONMASS),
    "RAD_CONST", H5T_NATIVE_DOUBLE, &(eagle->constants.RAD_CONST),
    "SEC_PER_MEGAYEAR", H5T_NATIVE_DOUBLE, &(eagle->constants.SEC_PER_MEGAYEAR),
    "SEC_PER_YEAR", H5T_NATIVE_DOUBLE, &(eagle->constants.SEC_PER_YEAR),
    "SOLAR_LUM", H5T_NATIVE_DOUBLE, &(eagle->constants.SOLAR_LUM),
    "SOLAR_MASS", H5T_NATIVE_DOUBLE, &(eagle->constants.SOLAR_MASS),
    "STEFAN", H5T_NATIVE_DOUBLE, &(eagle->constants.STEFAN),
    "THOMPSON", H5T_NATIVE_DOUBLE, &(eagle->constants.THOMPSON),
    "T_CMB0", H5T_NATIVE_DOUBLE, &(eagle->constants.T_CMB0),
    "Z_Solar", H5T_NATIVE_DOUBLE, &(eagle->constants.Z_Solar),
    NULL
  );

  read_h5attrs(
    file_id, "Parameters/ChemicalElements",
    "BG_NELEMENTS", H5T_NATIVE_INT, &(eagle->parameters.chemical_elements.BG_NELEMENTS),
    "CalciumOverSilicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.CalciumOverSilicon),
    "ElementNames", H5T_STRING, eagle->parameters.chemical_elements.ElementNames[0],
    "InitAbundance_Carbon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Carbon),
    "InitAbundance_Helium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Helium),
    "InitAbundance_Hydrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Hydrogen),
    "InitAbundance_Iron", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Iron),
    "InitAbundance_Magnesium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Magnesium),
    "InitAbundance_Neon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Neon),
    "InitAbundance_Nitrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Nitrogen),
    "InitAbundance_Oxygen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Oxygen),
    "InitAbundance_Silicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Silicon),
    "SolarAbundance", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance),
    "SolarAbundance_Calcium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Calcium),
    "SolarAbundance_Carbon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Carbon),
    "SolarAbundance_Helium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Helium),
    "SolarAbundance_Hydrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Hydrogen),
    "SolarAbundance_Iron", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Iron),
    "SolarAbundance_Magnesium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Magnesium),
    "SolarAbundance_Neon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Neon),
    "SolarAbundance_Nitrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Nitrogen),
    "SolarAbundance_Oxygen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Oxygen),
    "SolarAbundance_Silicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Silicon),
    "SolarAbundance_Sulphur", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Sulphur),
    "SulphurOverSilicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SulphurOverSilicon),
    NULL
  );

  read_h5attrs(
    file_id, "RuntimePars",
    "AGB_EnergyTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.AGB_EnergyTransferOn),
    "AGB_MassTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.AGB_MassTransferOn),
    "ArtBulkViscConst", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtBulkViscConst),
    "ArtBulkViscConstMin", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtBulkViscConstMin),
    "ArtDiffConst", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtDiffConst),
    "ArtDiffConstMin", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtDiffConstMin),
    "BHAllocFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BHAllocFactor),
    "BH_ConstantHeatTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_ConstantHeatTemp),
    "BH_MaxHeatLimit", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxHeatLimit),
    "BH_MaxHeatTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxHeatTemp),
    "BH_MaxMergingDistanceFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxMergingDistanceFactor),
    "BH_MaxRepositionDistanceFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxRepositionDistanceFactor),
    "BH_MinHeatLimit", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MinHeatLimit),
    "BH_MinHeatTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MinHeatTemp),
    "BH_feedback_mode", H5T_STRING, eagle->runtime_pars.BH_feedback_mode,
    "BH_maxHeatingProbability", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_maxHeatingProbability),
    "BlackHoleAccretionFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleAccretionFactor),
    "BlackHoleAccretionSlope", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleAccretionSlope),
    "BlackHoleEddingtonFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleEddingtonFactor),
    "BlackHoleFeedbackFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleFeedbackFactor),
    "BlackHoleMaxAccretionRadius", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleMaxAccretionRadius),
    "BlackHoleNgbFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleNgbFactor),
    "BlackHoleNumberOfNeighboursToHeat", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleNumberOfNeighboursToHeat),
    "BlackHoleRadiativeEfficiency", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleRadiativeEfficiency),
    "BlackHoleViscousAlpha", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleViscousAlpha),
    "BoxSize", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BoxSize),
    "BufferSize", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BufferSize),
    "CalciumOverSilicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.CalciumOverSilicon),
    "ComovingIntegrationOn", H5T_NATIVE_INT, &(eagle->runtime_pars.ComovingIntegrationOn),
    "CoolTablePath", H5T_STRING, eagle->runtime_pars.CoolTablePath,
    "CoolingOn", H5T_NATIVE_INT, &(eagle->runtime_pars.CoolingOn),
    "CourantFac", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.CourantFac),
    "CpuFile", H5T_STRING, eagle->runtime_pars.CpuFile,
    "CpuTimeBetRestartFile", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.CpuTimeBetRestartFile),
    "DesLinkNgb", H5T_NATIVE_INT, &(eagle->runtime_pars.DesLinkNgb),
    "DesNumNgb", H5T_NATIVE_INT, &(eagle->runtime_pars.DesNumNgb),
    "DesNumNgbStar", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.DesNumNgbStar),
    "DesNumNgbYoungStar", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.DesNumNgbYoungStar),
    "EOS_Cool_GammaEffective", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_GammaEffective),
    "EOS_Cool_MinOverDens", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_MinOverDens),
    "EOS_Cool_MinPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_MinPhysDens_HpCM3),
    "EOS_Cool_TempNorm_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_TempNorm_K),
    "EOS_Jeans_GammaEffective", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_GammaEffective),
    "EOS_Jeans_MinOverDens", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_MinOverDens),
    "EOS_Jeans_MinPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_MinPhysDens_HpCM3),
    "EOS_Jeans_TempNorm_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_TempNorm_K),
    "EOS_NormPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_NormPhysDens_HpCM3),
    "EnergyFile", H5T_STRING, eagle->runtime_pars.EnergyFile,
    "ErrTolForceAcc", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolForceAcc),
    "ErrTolIntAccuracy", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolIntAccuracy),
    "ErrTolTheta", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolTheta),
    "ErrTolThetaSubfind", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolThetaSubfind),
    "ExtraOutputListFilename", H5T_STRING, eagle->runtime_pars.ExtraOutputListFilename,
    "FoFFormat", H5T_NATIVE_INT, &(eagle->runtime_pars.FoFFormat),
    "FoFOutputListOn", H5T_NATIVE_INT, &(eagle->runtime_pars.FoFOutputListOn),
    "Generations", H5T_NATIVE_INT, &(eagle->runtime_pars.Generations),
    "GravityConstantInternal", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.GravityConstantInternal),
    "HubbleParam", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.HubbleParam),
    "ICFormat", H5T_NATIVE_INT, &(eagle->runtime_pars.ICFormat),
    "IMF_Exponent", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.IMF_Exponent),
    "IMF_LifetimeModel", H5T_STRING, eagle->runtime_pars.IMF_LifetimeModel,
    "IMF_MaxMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.IMF_MaxMass_MSUN),
    "IMF_MinMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.IMF_MinMass_MSUN),
    "IMF_Model", H5T_STRING, eagle->runtime_pars.IMF_Model,
    "InfoFile", H5T_STRING, eagle->runtime_pars.InfoFile,
    "InitAbundance_Carbon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Carbon),
    "InitAbundance_Helium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Helium),
    "InitAbundance_Hydrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Hydrogen),
    "InitAbundance_Iron", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Iron),
    "InitAbundance_Magnesium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Magnesium),
    "InitAbundance_Neon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Neon),
    "InitAbundance_Nitrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Nitrogen),
    "InitAbundance_Oxygen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Oxygen),
    "InitAbundance_Silicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Silicon),
    "InitCondFile", H5T_STRING, eagle->runtime_pars.InitCondFile,
    "InitGasTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitGasTemp),
    "InitMetallicity", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitMetallicity),
    "MaxMemSize", H5T_NATIVE_INT, &(eagle->runtime_pars.MaxMemSize),
    "MaxNumNgbDeviation", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxNumNgbDeviation),
    "MaxRMSDisplacementFac", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxRMSDisplacementFac),
    "MaxSizeTimestep", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxSizeTimestep),
    "MaxSmoothingLengthChange", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxSmoothingLengthChange),
    "MetAllocFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MetAllocFactor),
    "MetDepCoolingOn", H5T_NATIVE_INT, &(eagle->runtime_pars.MetDepCoolingOn),
    "MinFoFMassForNewSeed_Msun", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinFoFMassForNewSeed_Msun),
    "MinGasHsmlFractional", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinGasHsmlFractional),
    "MinGasTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinGasTemp),
    "MinSizeTimestep", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinSizeTimestep),
    "NumFilesPerSnapshot", H5T_NATIVE_INT, &(eagle->runtime_pars.NumFilesPerSnapshot),
    "NumFilesWrittenInParallel", H5T_NATIVE_INT, &(eagle->runtime_pars.NumFilesWrittenInParallel),
    "Omega0", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.Omega0),
    "OmegaBaryon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.OmegaBaryon),
    "OmegaLambda", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.OmegaLambda),
    "OutputDir", H5T_STRING, eagle->runtime_pars.OutputDir,
    "OutputListFilename", H5T_STRING, eagle->runtime_pars.OutputListFilename,
    "OutputListOn", H5T_NATIVE_INT, &(eagle->runtime_pars.OutputListOn),
    "PartAllocFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.PartAllocFactor),
    "PeriodicBoundariesOn", H5T_NATIVE_INT, &(eagle->runtime_pars.PeriodicBoundariesOn),
    "REION_H_Heating_EVpH", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_H_Heating_EVpH),
    "REION_H_ZCenter", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_H_ZCenter),
    "REION_He_Heating_EVpH", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_He_Heating_EVpH),
    "REION_He_ZCenter", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_He_ZCenter),
    "REION_He_ZSigma", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_He_ZSigma),
    "RestartFile", H5T_STRING, eagle->runtime_pars.RestartFile,
    "ResubmitCommand", H5T_STRING, eagle->runtime_pars.ResubmitCommand,
    "ResubmitOn", H5T_NATIVE_INT, &(eagle->runtime_pars.ResubmitOn),
    "RunLabel", H5T_STRING, eagle->runtime_pars.RunLabel,
    "SF_SchmidtLawCoeff_MSUNpYRpKPC2", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawCoeff_MSUNpYRpKPC2),
    "SF_SchmidtLawExponent", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawExponent),
    "SF_SchmidtLawHighDensExponent", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawHighDensExponent),
    "SF_SchmidtLawHighDensThresh_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawHighDensThresh_HpCM3),
    "SF_THRESH_MaxPhysDensOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SF_THRESH_MaxPhysDensOn),
    "SF_THRESH_MaxPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MaxPhysDens_HpCM3),
    "SF_THRESH_MetDepSFThreshMaxThresh_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MetDepSFThreshMaxThresh_HpCM3),
    "SF_THRESH_MetDepSFThreshNorm_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MetDepSFThreshNorm_HpCM3),
    "SF_THRESH_MetDepSFThreshSlope", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MetDepSFThreshSlope),
    "SF_THRESH_MinOverDens", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MinOverDens),
    "SF_THRESH_MinPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MinPhysDens_HpCM3),
    "SF_THRESH_TempMargin_DEX", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_TempMargin_DEX),
    "SNII_Delta_T_Divided_By_T_Vir", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Delta_T_Divided_By_T_Vir),
    "SNII_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Delta_T_K),
    "SNII_EnergyTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNII_EnergyTransferOn),
    "SNII_Energy_ERG", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Energy_ERG),
    "SNII_Factor_Carbon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Carbon),
    "SNII_Factor_Helium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Helium),
    "SNII_Factor_Hydrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Hydrogen),
    "SNII_Factor_Iron", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Iron),
    "SNII_Factor_Magnesium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Magnesium),
    "SNII_Factor_Neon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Neon),
    "SNII_Factor_Nitrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Nitrogen),
    "SNII_Factor_Oxygen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Oxygen),
    "SNII_Factor_Silicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Silicon),
    "SNII_MassTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNII_MassTransferOn),
    "SNII_MaxEnergyFraction", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MaxEnergyFraction),
    "SNII_MaxMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MaxMass_MSUN),
    "SNII_Max_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Max_Delta_T_K),
    "SNII_MinEnergyFraction", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MinEnergyFraction),
    "SNII_MinMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MinMass_MSUN),
    "SNII_Min_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Min_Delta_T_K),
    "SNII_Tvir0_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Tvir0_K),
    "SNII_Width_logTvir_dex", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Width_logTvir_dex),
    "SNII_WindDelay_YR", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_WindDelay_YR),
    "SNII_WindIsotropicOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNII_WindIsotropicOn),
    "SNII_exponent_Delta_T", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_exponent_Delta_T),
    "SNII_normalisation_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_normalisation_Delta_T_K),
    "SNII_rhogas_physdensnormfac", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_rhogas_physdensnormfac),
    "SNII_rhogas_power", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_rhogas_power),
    "SNII_zdep_power", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_zdep_power),
    "SNIa_Efficiency", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_Efficiency),
    "SNIa_EjectaVelocity_KMpS", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_EjectaVelocity_KMpS),
    "SNIa_EnergyFraction", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_EnergyFraction),
    "SNIa_EnergyTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNIa_EnergyTransferOn),
    "SNIa_EnergyTransferStochastic", H5T_NATIVE_INT, &(eagle->runtime_pars.SNIa_EnergyTransferStochastic),
    "SNIa_Energy_ERG", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_Energy_ERG),
    "SNIa_MassTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNIa_MassTransferOn),
    "SNIa_Model", H5T_STRING, eagle->runtime_pars.SNIa_Model,
    "SNIa_TimeScale", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_TimeScale),
    "SeedBlackHoleMass_Msun", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SeedBlackHoleMass_Msun),
    "SmallOutputListOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SmallOutputListOn),
    "SmallOutputTar", H5T_NATIVE_INT, &(eagle->runtime_pars.SmallOutputTar),
    "SmallSnapshotFileBase", H5T_STRING, eagle->runtime_pars.SmallSnapshotFileBase,
    "SnapFormat", H5T_NATIVE_INT, &(eagle->runtime_pars.SnapFormat),
    "SnapshotFileBase", H5T_STRING, eagle->runtime_pars.SnapshotFileBase,
    "SofteningBndry", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBndry),
    "SofteningBndryMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBndryMaxPhys),
    "SofteningBulge", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBulge),
    "SofteningBulgeMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBulgeMaxPhys),
    "SofteningDisk", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningDisk),
    "SofteningDiskMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningDiskMaxPhys),
    "SofteningGas", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningGas),
    "SofteningGasMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningGasMaxPhys),
    "SofteningHalo", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningHalo),
    "SofteningHaloMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningHaloMaxPhys),
    "SofteningStars", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningStars),
    "SofteningStarsMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningStarsMaxPhys),
    "StarformationOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StarformationOn),
    "StellarEnergyFeedbackOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarEnergyFeedbackOn),
    "StellarEvol_FeedbackOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarEvol_FeedbackOn),
    "StellarEvolutionCut_Gyr", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.StellarEvolutionCut_Gyr),
    "StellarEvolutionTimestepInterval", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarEvolutionTimestepInterval),
    "StellarMetalFeedbackOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarMetalFeedbackOn),
    "SulphurOverSilicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SulphurOverSilicon),
    "TimeBegin", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBegin),
    "TimeBetGridOutput", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetGridOutput),
    "TimeBetLineOfSight", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetLineOfSight),
    "TimeBetOnTheFlyFoF", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetOnTheFlyFoF),
    "TimeBetSmallSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetSmallSnapshot),
    "TimeBetSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetSnapshot),
    "TimeBetStatistics", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetStatistics),
    "TimeLimitCPU", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeLimitCPU),
    "TimeMax", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeMax),
    "TimeOfFirstGridOutput", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstGridOutput),
    "TimeOfFirstLineOfSight", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstLineOfSight),
    "TimeOfFirstSmallSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstSmallSnapshot),
    "TimeOfFirstSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstSnapshot),
    "TimebinFile", H5T_STRING, eagle->runtime_pars.TimebinFile,
    "TimingsFile", H5T_STRING, eagle->runtime_pars.TimingsFile,
    "TreeDomainUpdateFrequency", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TreeDomainUpdateFrequency),
    "TypeOfOpeningCriterion", H5T_NATIVE_INT, &(eagle->runtime_pars.TypeOfOpeningCriterion),
    "TypeOfTimestepCriterion", H5T_NATIVE_INT, &(eagle->runtime_pars.TypeOfTimestepCriterion),
    "UnitLength_in_cm", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.UnitLength_in_cm),
    "UnitMass_in_g", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.UnitMass_in_g),
    "UnitVelocity_in_cm_per_s", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.UnitVelocity_in_cm_per_s),
    "YieldTablePath", H5T_STRING, eagle->runtime_pars.YieldTablePath,
    "massDMpart", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.massDMpart),
    "stellar_feedback_DeltaT", H5T_STRING, eagle->runtime_pars.stellar_feedback_DeltaT,
    "stellar_feedback_mode", H5T_STRING, eagle->runtime_pars.stellar_feedback_mode,
    "stellar_feedback_tvir", H5T_STRING, eagle->runtime_pars.stellar_feedback_tvir,
    NULL);

  read_h5attrs(
    file_id, "Config",
    "Config_option_000", H5T_STRING, eagle->config.Config_option_000,
    "Config_option_001", H5T_STRING, eagle->config.Config_option_001,
    "Config_option_002", H5T_STRING, eagle->config.Config_option_002,
    "Config_option_003", H5T_STRING, eagle->config.Config_option_003,
    "Config_option_004", H5T_STRING, eagle->config.Config_option_004,
    "Config_option_005", H5T_STRING, eagle->config.Config_option_005,
    "Config_option_006", H5T_STRING, eagle->config.Config_option_006,
    "Config_option_007", H5T_STRING, eagle->config.Config_option_007,
    "Config_option_008", H5T_STRING, eagle->config.Config_option_008,
    "Config_option_009", H5T_STRING, eagle->config.Config_option_009,
    "Config_option_010", H5T_STRING, eagle->config.Config_option_010,
    "Config_option_011", H5T_STRING, eagle->config.Config_option_011,
    "Config_option_012", H5T_STRING, eagle->config.Config_option_012,
    "Config_option_013", H5T_STRING, eagle->config.Config_option_013,
    "Config_option_014", H5T_STRING, eagle->config.Config_option_014,
    "Config_option_015", H5T_STRING, eagle->config.Config_option_015,
    "Config_option_016", H5T_STRING, eagle->config.Config_option_016,
    "Config_option_017", H5T_STRING, eagle->config.Config_option_017,
    "Config_option_018", H5T_STRING, eagle->config.Config_option_018,
    "Config_option_019", H5T_STRING, eagle->config.Config_option_019,
    "Config_option_020", H5T_STRING, eagle->config.Config_option_020,
    "Config_option_021", H5T_STRING, eagle->config.Config_option_021,
    "Config_option_022", H5T_STRING, eagle->config.Config_option_022,
    "Config_option_023", H5T_STRING, eagle->config.Config_option_023,
    "Config_option_024", H5T_STRING, eagle->config.Config_option_024,
    "Config_option_025", H5T_STRING, eagle->config.Config_option_025,
    "Config_option_026", H5T_STRING, eagle->config.Config_option_026,
    "Config_option_027", H5T_STRING, eagle->config.Config_option_027,
    "Config_option_028", H5T_STRING, eagle->config.Config_option_028,
    "Config_option_029", H5T_STRING, eagle->config.Config_option_029,
    "Config_option_030", H5T_STRING, eagle->config.Config_option_030,
    "Config_option_031", H5T_STRING, eagle->config.Config_option_031,
    "Config_option_032", H5T_STRING, eagle->config.Config_option_032,
    "Config_option_033", H5T_STRING, eagle->config.Config_option_033,
    "Config_option_034", H5T_STRING, eagle->config.Config_option_034,
    "Config_option_035", H5T_STRING, eagle->config.Config_option_035,
    "Config_option_036", H5T_STRING, eagle->config.Config_option_036,
    "Config_option_037", H5T_STRING, eagle->config.Config_option_037,
    "Config_option_038", H5T_STRING, eagle->config.Config_option_038,
    "Config_option_039", H5T_STRING, eagle->config.Config_option_039,
    "Config_option_040", H5T_STRING, eagle->config.Config_option_040,
    "Config_option_041", H5T_STRING, eagle->config.Config_option_041,
    "Config_option_042", H5T_STRING, eagle->config.Config_option_042,
    "Config_option_043", H5T_STRING, eagle->config.Config_option_043,
    "Config_option_044", H5T_STRING, eagle->config.Config_option_044,
    "Config_option_045", H5T_STRING, eagle->config.Config_option_045,
    "Config_option_046", H5T_STRING, eagle->config.Config_option_046,
    "Config_option_047", H5T_STRING, eagle->config.Config_option_047,
    "Config_option_048", H5T_STRING, eagle->config.Config_option_048,
    "Config_option_049", H5T_STRING, eagle->config.Config_option_049,
    "Config_option_050", H5T_STRING, eagle->config.Config_option_050,
    "Config_option_051", H5T_STRING, eagle->config.Config_option_051,
    "Config_option_052", H5T_STRING, eagle->config.Config_option_052,
    "Config_option_053", H5T_STRING, eagle->config.Config_option_053,
    "Config_option_054", H5T_STRING, eagle->config.Config_option_054,
    "Config_option_055", H5T_STRING, eagle->config.Config_option_055,
    "Config_option_056", H5T_STRING, eagle->config.Config_option_056,
    "Config_option_057", H5T_STRING, eagle->config.Config_option_057,
    "Config_option_058", H5T_STRING, eagle->config.Config_option_058,
    "Config_option_059", H5T_STRING, eagle->config.Config_option_059,
    "SVN_Version", H5T_STRING, eagle->config.SVN_Version,
    NULL);

  return file_id;
}
