/*
 * init_eagle.c
 * tests_file: init_eagle_tests.c
 *
 * Initialize the package by loading the snapshot general info (header,
 * constants, etc)
 *
 * @param: file_path: Formatted file path, e.g. /path/to/snap.%d.h5
 * @param: eagle: An eagle object to be filled
 *
 * @return: Standard EXIT_SUCCESS (EXIT_FAILURE on errors)
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <High5/High5.h>
#include <assert.h>
#include "./init_eagle.h"


#ifndef PRINT
#define PRINT printf
#endif


hid_t init_eagle(char *file_path_fmt, eagle_t *eagle)
{
  if(strstr(file_path_fmt, "%d") == NULL) {
    printf("[Warning] Please use a formatted file path.\n");
    printf("          e.g. /path/to/eagle/snap.%%d.h5\n");
    return EXIT_FAILURE;
  }

  char file_path[1024];
  sprintf(file_path, file_path_fmt, 0);

  hid_t file_id = open_h5(file_path, H5F_ACC_RDONLY, H5P_DEFAULT);
  int high5err, status = EXIT_SUCCESS;

  high5err = read_h5attrs(
    file_id, "Header",
    "BoxSize", H5T_NATIVE_DOUBLE, &(eagle->header.BoxSize), optional_attr,
    "E(z)", H5T_NATIVE_DOUBLE, &(eagle->header.E_z), optional_attr,
    "ExpansionFactor", H5T_NATIVE_DOUBLE, &(eagle->header.ExpansionFactor), optional_attr,
    "H(z)", H5T_NATIVE_DOUBLE, &(eagle->header.H_z), optional_attr,
    "HubbleParam", H5T_NATIVE_DOUBLE, &(eagle->header.HubbleParam), required_attr,
    "Omega0", H5T_NATIVE_DOUBLE, &(eagle->header.Omega0), optional_attr,
    "OmegaBaryon", H5T_NATIVE_DOUBLE, &(eagle->header.OmegaBaryon), required_attr,
    "OmegaLambda", H5T_NATIVE_DOUBLE, &(eagle->header.OmegaLambda), optional_attr,
    "Redshift", H5T_NATIVE_DOUBLE, &(eagle->header.Redshift), required_attr,
    "Time", H5T_NATIVE_DOUBLE, &(eagle->header.Time), required_attr,
    "MassTable", H5T_NATIVE_DOUBLE, eagle->header.MassTable, optional_attr,
    "Flag_Cooling", H5T_NATIVE_INT, &(eagle->header.Flag_Cooling), optional_attr,
    "Flag_DoublePrecision", H5T_NATIVE_INT, &(eagle->header.Flag_DoublePrecision), optional_attr,
    "Flag_Feedback", H5T_NATIVE_INT, &(eagle->header.Flag_Feedback), optional_attr,
    "Flag_IC_Info", H5T_NATIVE_INT, &(eagle->header.Flag_IC_Info), optional_attr,
    "Flag_Metals", H5T_NATIVE_INT, &(eagle->header.Flag_Metals), optional_attr,
    "Flag_Sfr", H5T_NATIVE_INT, &(eagle->header.Flag_Sfr), optional_attr,
    "Flag_StellarAge", H5T_NATIVE_INT, &(eagle->header.Flag_StellarAge), optional_attr,
    "NumFilesPerSnapshot", H5T_NATIVE_INT, &(eagle->header.NumFilesPerSnapshot), required_attr,
    "NumPart_ThisFile", H5T_NATIVE_INT, eagle->header.NumPart_ThisFile, required_attr,
    "NumPart_Total", H5T_NATIVE_INT, eagle->header.NumPart_Total, required_attr,
    "NumPart_Total_HighWord", H5T_NATIVE_INT, eagle->header.NumPart_Total_HighWord, optional_attr,
    "RunLabel", H5T_STRING, eagle->header.RunLabel, optional_attr,
    NULL
  );

  if(high5err == EXIT_FAILURE)
    status = EXIT_FAILURE;

  high5err = read_h5attrs(
    file_id, "Units",
    "UnitDensity_in_cgs", H5T_NATIVE_DOUBLE, &(eagle->units.UnitDensity_in_cgs), required_attr,
    "UnitEnergy_in_cgs", H5T_NATIVE_DOUBLE, &(eagle->units.UnitEnergy_in_cgs), required_attr,
    "UnitLength_in_cm", H5T_NATIVE_DOUBLE, &(eagle->units.UnitLength_in_cm), required_attr,
    "UnitMass_in_g", H5T_NATIVE_DOUBLE, &(eagle->units.UnitMass_in_g), required_attr,
    "UnitPressure_in_cgs", H5T_NATIVE_DOUBLE, &(eagle->units.UnitPressure_in_cgs), required_attr,
    "UnitTime_in_s", H5T_NATIVE_DOUBLE, &(eagle->units.UnitTime_in_s), required_attr,
    "UnitVelocity_in_cm_per_s", H5T_NATIVE_DOUBLE, &(eagle->units.UnitVelocity_in_cm_per_s), required_attr,
    NULL
  );

  if(high5err == EXIT_FAILURE)
    status = EXIT_FAILURE;

  high5err = read_h5attrs(
    file_id, "Constants",
    "AVOGADRO", H5T_NATIVE_DOUBLE, &(eagle->constants.AVOGADRO), optional_attr,
    "BOLTZMANN", H5T_NATIVE_DOUBLE, &(eagle->constants.BOLTZMANN), optional_attr,
    "C", H5T_NATIVE_DOUBLE, &(eagle->constants.C), optional_attr,
    "CM_PER_MPC", H5T_NATIVE_DOUBLE, &(eagle->constants.CM_PER_MPC), optional_attr,
    "ELECTRONCHARGE", H5T_NATIVE_DOUBLE, &(eagle->constants.ELECTRONCHARGE), optional_attr,
    "ELECTRONMASS", H5T_NATIVE_DOUBLE, &(eagle->constants.ELECTRONMASS), optional_attr,
    "EV_TO_ERG", H5T_NATIVE_DOUBLE, &(eagle->constants.EV_TO_ERG), optional_attr,
    "GAMMA", H5T_NATIVE_DOUBLE, &(eagle->constants.GAMMA), optional_attr,
    "GAS_CONST", H5T_NATIVE_DOUBLE, &(eagle->constants.GAS_CONST), optional_attr,
    "GRAVITY", H5T_NATIVE_DOUBLE, &(eagle->constants.GRAVITY), required_attr,
    "HUBBLE", H5T_NATIVE_DOUBLE, &(eagle->constants.HUBBLE), required_attr,
    "PI", H5T_NATIVE_DOUBLE, &(eagle->constants.PI), required_attr,
    "PLANCK", H5T_NATIVE_DOUBLE, &(eagle->constants.PLANCK), optional_attr,
    "PROTONMASS", H5T_NATIVE_DOUBLE, &(eagle->constants.PROTONMASS), required_attr,
    "RAD_CONST", H5T_NATIVE_DOUBLE, &(eagle->constants.RAD_CONST), optional_attr,
    "SEC_PER_MEGAYEAR", H5T_NATIVE_DOUBLE, &(eagle->constants.SEC_PER_MEGAYEAR), optional_attr,
    "SEC_PER_YEAR", H5T_NATIVE_DOUBLE, &(eagle->constants.SEC_PER_YEAR), optional_attr,
    "SOLAR_LUM", H5T_NATIVE_DOUBLE, &(eagle->constants.SOLAR_LUM), optional_attr,
    "SOLAR_MASS", H5T_NATIVE_DOUBLE, &(eagle->constants.SOLAR_MASS), required_attr,
    "STEFAN", H5T_NATIVE_DOUBLE, &(eagle->constants.STEFAN), optional_attr,
    "THOMPSON", H5T_NATIVE_DOUBLE, &(eagle->constants.THOMPSON), optional_attr,
    "T_CMB0", H5T_NATIVE_DOUBLE, &(eagle->constants.T_CMB0), optional_attr,
    "Z_Solar", H5T_NATIVE_DOUBLE, &(eagle->constants.Z_Solar), optional_attr,
    NULL
  );

  if(high5err == EXIT_FAILURE)
    status = EXIT_FAILURE;

  high5err = read_h5attrs(
    file_id, "Parameters/ChemicalElements",
    "BG_NELEMENTS", H5T_NATIVE_INT, &(eagle->parameters.chemical_elements.BG_NELEMENTS), optional_attr,
    "CalciumOverSilicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.CalciumOverSilicon), optional_attr,
    "ElementNames", H5T_STRING, eagle->parameters.chemical_elements.ElementNames[0], optional_attr,
    "InitAbundance_Carbon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Carbon), optional_attr,
    "InitAbundance_Helium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Helium), optional_attr,
    "InitAbundance_Hydrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Hydrogen), optional_attr,
    "InitAbundance_Iron", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Iron), optional_attr,
    "InitAbundance_Magnesium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Magnesium), optional_attr,
    "InitAbundance_Neon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Neon), optional_attr,
    "InitAbundance_Nitrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Nitrogen), optional_attr,
    "InitAbundance_Oxygen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Oxygen), optional_attr,
    "InitAbundance_Silicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.InitAbundance_Silicon), optional_attr,
    "SolarAbundance", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance), optional_attr,
    "SolarAbundance_Calcium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Calcium), optional_attr,
    "SolarAbundance_Carbon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Carbon), optional_attr,
    "SolarAbundance_Helium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Helium), optional_attr,
    "SolarAbundance_Hydrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Hydrogen), optional_attr,
    "SolarAbundance_Iron", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Iron), optional_attr,
    "SolarAbundance_Magnesium", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Magnesium), optional_attr,
    "SolarAbundance_Neon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Neon), optional_attr,
    "SolarAbundance_Nitrogen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Nitrogen), optional_attr,
    "SolarAbundance_Oxygen", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Oxygen), optional_attr,
    "SolarAbundance_Silicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Silicon), optional_attr,
    "SolarAbundance_Sulphur", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SolarAbundance_Sulphur), optional_attr,
    "SulphurOverSilicon", H5T_NATIVE_DOUBLE, &(eagle->parameters.chemical_elements.SulphurOverSilicon), optional_attr,
    NULL
  );

  if(high5err == EXIT_FAILURE)
    status = EXIT_FAILURE;

  high5err = read_h5attrs(
    file_id, "RuntimePars",
    "AGB_EnergyTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.AGB_EnergyTransferOn), optional_attr,
    "AGB_MassTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.AGB_MassTransferOn), optional_attr,
    "ArtBulkViscConst", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtBulkViscConst), optional_attr,
    "ArtBulkViscConstMin", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtBulkViscConstMin), optional_attr,
    "ArtDiffConst", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtDiffConst), optional_attr,
    "ArtDiffConstMin", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ArtDiffConstMin), optional_attr,
    "BHAllocFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BHAllocFactor), optional_attr,
    "BH_ConstantHeatTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_ConstantHeatTemp), optional_attr,
    "BH_MaxHeatLimit", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxHeatLimit), optional_attr,
    "BH_MaxHeatTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxHeatTemp), optional_attr,
    "BH_MaxMergingDistanceFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxMergingDistanceFactor), optional_attr,
    "BH_MaxRepositionDistanceFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MaxRepositionDistanceFactor), optional_attr,
    "BH_MinHeatLimit", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MinHeatLimit), optional_attr,
    "BH_MinHeatTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_MinHeatTemp), optional_attr,
    "BH_feedback_mode", H5T_STRING, eagle->runtime_pars.BH_feedback_mode, optional_attr,
    "BH_maxHeatingProbability", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BH_maxHeatingProbability), optional_attr,
    "BlackHoleAccretionFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleAccretionFactor), optional_attr,
    "BlackHoleAccretionSlope", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleAccretionSlope), optional_attr,
    "BlackHoleEddingtonFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleEddingtonFactor), optional_attr,
    "BlackHoleFeedbackFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleFeedbackFactor), optional_attr,
    "BlackHoleMaxAccretionRadius", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleMaxAccretionRadius), optional_attr,
    "BlackHoleNgbFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleNgbFactor), optional_attr,
    "BlackHoleNumberOfNeighboursToHeat", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleNumberOfNeighboursToHeat), optional_attr,
    "BlackHoleRadiativeEfficiency", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleRadiativeEfficiency), optional_attr,
    "BlackHoleViscousAlpha", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BlackHoleViscousAlpha), optional_attr,
    "BoxSize", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BoxSize), optional_attr,
    "BufferSize", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.BufferSize), optional_attr,
    "CalciumOverSilicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.CalciumOverSilicon), optional_attr,
    "ComovingIntegrationOn", H5T_NATIVE_INT, &(eagle->runtime_pars.ComovingIntegrationOn), optional_attr,
    "CoolTablePath", H5T_STRING, eagle->runtime_pars.CoolTablePath, optional_attr,
    "CoolingOn", H5T_NATIVE_INT, &(eagle->runtime_pars.CoolingOn), optional_attr,
    "CourantFac", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.CourantFac), optional_attr,
    "CpuFile", H5T_STRING, eagle->runtime_pars.CpuFile, optional_attr,
    "CpuTimeBetRestartFile", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.CpuTimeBetRestartFile), optional_attr,
    "DesLinkNgb", H5T_NATIVE_INT, &(eagle->runtime_pars.DesLinkNgb), optional_attr,
    "DesNumNgb", H5T_NATIVE_INT, &(eagle->runtime_pars.DesNumNgb), optional_attr,
    "DesNumNgbStar", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.DesNumNgbStar), optional_attr,
    "DesNumNgbYoungStar", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.DesNumNgbYoungStar), optional_attr,
    "EOS_Cool_GammaEffective", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_GammaEffective), optional_attr,
    "EOS_Cool_MinOverDens", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_MinOverDens), optional_attr,
    "EOS_Cool_MinPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_MinPhysDens_HpCM3), optional_attr,
    "EOS_Cool_TempNorm_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Cool_TempNorm_K), optional_attr,
    "EOS_Jeans_GammaEffective", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_GammaEffective), optional_attr,
    "EOS_Jeans_MinOverDens", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_MinOverDens), optional_attr,
    "EOS_Jeans_MinPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_MinPhysDens_HpCM3), optional_attr,
    "EOS_Jeans_TempNorm_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_Jeans_TempNorm_K), optional_attr,
    "EOS_NormPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.EOS_NormPhysDens_HpCM3), optional_attr,
    "EnergyFile", H5T_STRING, eagle->runtime_pars.EnergyFile, optional_attr,
    "ErrTolForceAcc", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolForceAcc), optional_attr,
    "ErrTolIntAccuracy", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolIntAccuracy), optional_attr,
    "ErrTolTheta", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolTheta), optional_attr,
    "ErrTolThetaSubfind", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.ErrTolThetaSubfind), optional_attr,
    "ExtraOutputListFilename", H5T_STRING, eagle->runtime_pars.ExtraOutputListFilename, optional_attr,
    "FoFFormat", H5T_NATIVE_INT, &(eagle->runtime_pars.FoFFormat), optional_attr,
    "FoFOutputListOn", H5T_NATIVE_INT, &(eagle->runtime_pars.FoFOutputListOn), optional_attr,
    "Generations", H5T_NATIVE_INT, &(eagle->runtime_pars.Generations), optional_attr,
    "GravityConstantInternal", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.GravityConstantInternal), optional_attr,
    "HubbleParam", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.HubbleParam), optional_attr,
    "ICFormat", H5T_NATIVE_INT, &(eagle->runtime_pars.ICFormat), optional_attr,
    "IMF_Exponent", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.IMF_Exponent), optional_attr,
    "IMF_LifetimeModel", H5T_STRING, eagle->runtime_pars.IMF_LifetimeModel, optional_attr,
    "IMF_MaxMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.IMF_MaxMass_MSUN), optional_attr,
    "IMF_MinMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.IMF_MinMass_MSUN), optional_attr,
    "IMF_Model", H5T_STRING, eagle->runtime_pars.IMF_Model, optional_attr,
    "InfoFile", H5T_STRING, eagle->runtime_pars.InfoFile, optional_attr,
    "InitAbundance_Carbon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Carbon), optional_attr,
    "InitAbundance_Helium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Helium), required_attr,
    "InitAbundance_Hydrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Hydrogen), required_attr,
    "InitAbundance_Iron", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Iron), optional_attr,
    "InitAbundance_Magnesium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Magnesium), optional_attr,
    "InitAbundance_Neon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Neon), optional_attr,
    "InitAbundance_Nitrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Nitrogen), optional_attr,
    "InitAbundance_Oxygen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Oxygen), optional_attr,
    "InitAbundance_Silicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitAbundance_Silicon), optional_attr,
    "InitCondFile", H5T_STRING, eagle->runtime_pars.InitCondFile, optional_attr,
    "InitGasTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitGasTemp), optional_attr,
    "InitMetallicity", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.InitMetallicity), optional_attr,
    "MaxMemSize", H5T_NATIVE_INT, &(eagle->runtime_pars.MaxMemSize), optional_attr,
    "MaxNumNgbDeviation", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxNumNgbDeviation), optional_attr,
    "MaxRMSDisplacementFac", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxRMSDisplacementFac), optional_attr,
    "MaxSizeTimestep", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxSizeTimestep), optional_attr,
    "MaxSmoothingLengthChange", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MaxSmoothingLengthChange), optional_attr,
    "MetAllocFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MetAllocFactor), optional_attr,
    "MetDepCoolingOn", H5T_NATIVE_INT, &(eagle->runtime_pars.MetDepCoolingOn), optional_attr,
    "MinFoFMassForNewSeed_Msun", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinFoFMassForNewSeed_Msun), optional_attr,
    "MinGasHsmlFractional", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinGasHsmlFractional), optional_attr,
    "MinGasTemp", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinGasTemp), optional_attr,
    "MinSizeTimestep", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.MinSizeTimestep), optional_attr,
    "NumFilesPerSnapshot", H5T_NATIVE_INT, &(eagle->runtime_pars.NumFilesPerSnapshot), optional_attr,
    "NumFilesWrittenInParallel", H5T_NATIVE_INT, &(eagle->runtime_pars.NumFilesWrittenInParallel), optional_attr,
    "Omega0", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.Omega0), optional_attr,
    "OmegaBaryon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.OmegaBaryon), optional_attr,
    "OmegaLambda", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.OmegaLambda), optional_attr,
    "OutputDir", H5T_STRING, eagle->runtime_pars.OutputDir, optional_attr,
    "OutputListFilename", H5T_STRING, eagle->runtime_pars.OutputListFilename, optional_attr,
    "OutputListOn", H5T_NATIVE_INT, &(eagle->runtime_pars.OutputListOn), optional_attr,
    "PartAllocFactor", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.PartAllocFactor), optional_attr,
    "PeriodicBoundariesOn", H5T_NATIVE_INT, &(eagle->runtime_pars.PeriodicBoundariesOn), optional_attr,
    "REION_H_Heating_EVpH", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_H_Heating_EVpH), optional_attr,
    "REION_H_ZCenter", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_H_ZCenter), optional_attr,
    "REION_He_Heating_EVpH", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_He_Heating_EVpH), optional_attr,
    "REION_He_ZCenter", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_He_ZCenter), optional_attr,
    "REION_He_ZSigma", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.REION_He_ZSigma), optional_attr,
    "RestartFile", H5T_STRING, eagle->runtime_pars.RestartFile, optional_attr,
    "ResubmitCommand", H5T_STRING, eagle->runtime_pars.ResubmitCommand, optional_attr,
    "ResubmitOn", H5T_NATIVE_INT, &(eagle->runtime_pars.ResubmitOn), optional_attr,
    "RunLabel", H5T_STRING, eagle->runtime_pars.RunLabel, optional_attr,
    "SF_SchmidtLawCoeff_MSUNpYRpKPC2", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawCoeff_MSUNpYRpKPC2), optional_attr,
    "SF_SchmidtLawExponent", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawExponent), optional_attr,
    "SF_SchmidtLawHighDensExponent", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawHighDensExponent), optional_attr,
    "SF_SchmidtLawHighDensThresh_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_SchmidtLawHighDensThresh_HpCM3), optional_attr,
    "SF_THRESH_MaxPhysDensOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SF_THRESH_MaxPhysDensOn), optional_attr,
    "SF_THRESH_MaxPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MaxPhysDens_HpCM3), required_attr,
    "SF_THRESH_MetDepSFThreshMaxThresh_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MetDepSFThreshMaxThresh_HpCM3), optional_attr,
    "SF_THRESH_MetDepSFThreshNorm_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MetDepSFThreshNorm_HpCM3), optional_attr,
    "SF_THRESH_MetDepSFThreshSlope", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MetDepSFThreshSlope), optional_attr,
    "SF_THRESH_MinOverDens", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MinOverDens), optional_attr,
    "SF_THRESH_MinPhysDens_HpCM3", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_MinPhysDens_HpCM3), optional_attr,
    "SF_THRESH_TempMargin_DEX", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SF_THRESH_TempMargin_DEX), optional_attr,
    "SNII_Delta_T_Divided_By_T_Vir", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Delta_T_Divided_By_T_Vir), optional_attr,
    "SNII_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Delta_T_K), optional_attr,
    "SNII_EnergyTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNII_EnergyTransferOn), optional_attr,
    "SNII_Energy_ERG", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Energy_ERG), optional_attr,
    "SNII_Factor_Carbon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Carbon), optional_attr,
    "SNII_Factor_Helium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Helium), optional_attr,
    "SNII_Factor_Hydrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Hydrogen), optional_attr,
    "SNII_Factor_Iron", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Iron), optional_attr,
    "SNII_Factor_Magnesium", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Magnesium), optional_attr,
    "SNII_Factor_Neon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Neon), optional_attr,
    "SNII_Factor_Nitrogen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Nitrogen), optional_attr,
    "SNII_Factor_Oxygen", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Oxygen), optional_attr,
    "SNII_Factor_Silicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Factor_Silicon), optional_attr,
    "SNII_MassTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNII_MassTransferOn), optional_attr,
    "SNII_MaxEnergyFraction", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MaxEnergyFraction), optional_attr,
    "SNII_MaxMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MaxMass_MSUN), optional_attr,
    "SNII_Max_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Max_Delta_T_K), optional_attr,
    "SNII_MinEnergyFraction", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MinEnergyFraction), optional_attr,
    "SNII_MinMass_MSUN", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_MinMass_MSUN), optional_attr,
    "SNII_Min_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Min_Delta_T_K), optional_attr,
    "SNII_Tvir0_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Tvir0_K), optional_attr,
    "SNII_Width_logTvir_dex", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_Width_logTvir_dex), optional_attr,
    "SNII_WindDelay_YR", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_WindDelay_YR), optional_attr,
    "SNII_WindIsotropicOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNII_WindIsotropicOn), optional_attr,
    "SNII_exponent_Delta_T", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_exponent_Delta_T), optional_attr,
    "SNII_normalisation_Delta_T_K", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_normalisation_Delta_T_K), optional_attr,
    "SNII_rhogas_physdensnormfac", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_rhogas_physdensnormfac), optional_attr,
    "SNII_rhogas_power", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_rhogas_power), optional_attr,
    "SNII_zdep_power", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNII_zdep_power), optional_attr,
    "SNIa_Efficiency", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_Efficiency), optional_attr,
    "SNIa_EjectaVelocity_KMpS", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_EjectaVelocity_KMpS), optional_attr,
    "SNIa_EnergyFraction", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_EnergyFraction), optional_attr,
    "SNIa_EnergyTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNIa_EnergyTransferOn), optional_attr,
    "SNIa_EnergyTransferStochastic", H5T_NATIVE_INT, &(eagle->runtime_pars.SNIa_EnergyTransferStochastic), optional_attr,
    "SNIa_Energy_ERG", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_Energy_ERG), optional_attr,
    "SNIa_MassTransferOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SNIa_MassTransferOn), optional_attr,
    "SNIa_Model", H5T_STRING, eagle->runtime_pars.SNIa_Model, optional_attr,
    "SNIa_TimeScale", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SNIa_TimeScale), optional_attr,
    "SeedBlackHoleMass_Msun", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SeedBlackHoleMass_Msun), optional_attr,
    "SmallOutputListOn", H5T_NATIVE_INT, &(eagle->runtime_pars.SmallOutputListOn), optional_attr,
    "SmallOutputTar", H5T_NATIVE_INT, &(eagle->runtime_pars.SmallOutputTar), optional_attr,
    "SmallSnapshotFileBase", H5T_STRING, eagle->runtime_pars.SmallSnapshotFileBase, optional_attr,
    "SnapFormat", H5T_NATIVE_INT, &(eagle->runtime_pars.SnapFormat), optional_attr,
    "SnapshotFileBase", H5T_STRING, eagle->runtime_pars.SnapshotFileBase, optional_attr,
    "SofteningBndry", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBndry), optional_attr,
    "SofteningBndryMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBndryMaxPhys), optional_attr,
    "SofteningBulge", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBulge), optional_attr,
    "SofteningBulgeMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningBulgeMaxPhys), optional_attr,
    "SofteningDisk", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningDisk), optional_attr,
    "SofteningDiskMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningDiskMaxPhys), optional_attr,
    "SofteningGas", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningGas), optional_attr,
    "SofteningGasMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningGasMaxPhys), optional_attr,
    "SofteningHalo", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningHalo), optional_attr,
    "SofteningHaloMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningHaloMaxPhys), optional_attr,
    "SofteningStars", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningStars), optional_attr,
    "SofteningStarsMaxPhys", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SofteningStarsMaxPhys), optional_attr,
    "StarformationOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StarformationOn), optional_attr,
    "StellarEnergyFeedbackOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarEnergyFeedbackOn), optional_attr,
    "StellarEvol_FeedbackOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarEvol_FeedbackOn), optional_attr,
    "StellarEvolutionCut_Gyr", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.StellarEvolutionCut_Gyr), optional_attr,
    "StellarEvolutionTimestepInterval", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarEvolutionTimestepInterval), optional_attr,
    "StellarMetalFeedbackOn", H5T_NATIVE_INT, &(eagle->runtime_pars.StellarMetalFeedbackOn), optional_attr,
    "SulphurOverSilicon", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.SulphurOverSilicon), optional_attr,
    "TimeBegin", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBegin), optional_attr,
    "TimeBetGridOutput", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetGridOutput), optional_attr,
    "TimeBetLineOfSight", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetLineOfSight), optional_attr,
    "TimeBetOnTheFlyFoF", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetOnTheFlyFoF), optional_attr,
    "TimeBetSmallSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetSmallSnapshot), optional_attr,
    "TimeBetSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetSnapshot), optional_attr,
    "TimeBetStatistics", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeBetStatistics), optional_attr,
    "TimeLimitCPU", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeLimitCPU), optional_attr,
    "TimeMax", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeMax), optional_attr,
    "TimeOfFirstGridOutput", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstGridOutput), optional_attr,
    "TimeOfFirstLineOfSight", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstLineOfSight), optional_attr,
    "TimeOfFirstSmallSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstSmallSnapshot), optional_attr,
    "TimeOfFirstSnapshot", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TimeOfFirstSnapshot), optional_attr,
    "TimebinFile", H5T_STRING, eagle->runtime_pars.TimebinFile, optional_attr,
    "TimingsFile", H5T_STRING, eagle->runtime_pars.TimingsFile, optional_attr,
    "TreeDomainUpdateFrequency", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.TreeDomainUpdateFrequency), optional_attr,
    "TypeOfOpeningCriterion", H5T_NATIVE_INT, &(eagle->runtime_pars.TypeOfOpeningCriterion), optional_attr,
    "TypeOfTimestepCriterion", H5T_NATIVE_INT, &(eagle->runtime_pars.TypeOfTimestepCriterion), optional_attr,
    "UnitLength_in_cm", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.UnitLength_in_cm), optional_attr,
    "UnitMass_in_g", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.UnitMass_in_g), optional_attr,
    "UnitVelocity_in_cm_per_s", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.UnitVelocity_in_cm_per_s), optional_attr,
    "YieldTablePath", H5T_STRING, eagle->runtime_pars.YieldTablePath, optional_attr,
    "massDMpart", H5T_NATIVE_FLOAT, &(eagle->runtime_pars.massDMpart), optional_attr,
    "stellar_feedback_DeltaT", H5T_STRING, eagle->runtime_pars.stellar_feedback_DeltaT, optional_attr,
    "stellar_feedback_mode", H5T_STRING, eagle->runtime_pars.stellar_feedback_mode, optional_attr,
    "stellar_feedback_tvir", H5T_STRING, eagle->runtime_pars.stellar_feedback_tvir, optional_attr,
    NULL);

  if(high5err == EXIT_FAILURE)
    status = EXIT_FAILURE;

  high5err = read_h5attrs(
    file_id, "Config",
    "Config_option_000", H5T_STRING, eagle->config.Config_option_000, optional_attr,
    "Config_option_001", H5T_STRING, eagle->config.Config_option_001, optional_attr,
    "Config_option_002", H5T_STRING, eagle->config.Config_option_002, optional_attr,
    "Config_option_003", H5T_STRING, eagle->config.Config_option_003, optional_attr,
    "Config_option_004", H5T_STRING, eagle->config.Config_option_004, optional_attr,
    "Config_option_005", H5T_STRING, eagle->config.Config_option_005, optional_attr,
    "Config_option_006", H5T_STRING, eagle->config.Config_option_006, optional_attr,
    "Config_option_007", H5T_STRING, eagle->config.Config_option_007, optional_attr,
    "Config_option_008", H5T_STRING, eagle->config.Config_option_008, optional_attr,
    "Config_option_009", H5T_STRING, eagle->config.Config_option_009, optional_attr,
    "Config_option_010", H5T_STRING, eagle->config.Config_option_010, optional_attr,
    "Config_option_011", H5T_STRING, eagle->config.Config_option_011, optional_attr,
    "Config_option_012", H5T_STRING, eagle->config.Config_option_012, optional_attr,
    "Config_option_013", H5T_STRING, eagle->config.Config_option_013, optional_attr,
    "Config_option_014", H5T_STRING, eagle->config.Config_option_014, optional_attr,
    "Config_option_015", H5T_STRING, eagle->config.Config_option_015, optional_attr,
    "Config_option_016", H5T_STRING, eagle->config.Config_option_016, optional_attr,
    "Config_option_017", H5T_STRING, eagle->config.Config_option_017, optional_attr,
    "Config_option_018", H5T_STRING, eagle->config.Config_option_018, optional_attr,
    "Config_option_019", H5T_STRING, eagle->config.Config_option_019, optional_attr,
    "Config_option_020", H5T_STRING, eagle->config.Config_option_020, optional_attr,
    "Config_option_021", H5T_STRING, eagle->config.Config_option_021, optional_attr,
    "Config_option_022", H5T_STRING, eagle->config.Config_option_022, optional_attr,
    "Config_option_023", H5T_STRING, eagle->config.Config_option_023, optional_attr,
    "Config_option_024", H5T_STRING, eagle->config.Config_option_024, optional_attr,
    "Config_option_025", H5T_STRING, eagle->config.Config_option_025, optional_attr,
    "Config_option_026", H5T_STRING, eagle->config.Config_option_026, optional_attr,
    "Config_option_027", H5T_STRING, eagle->config.Config_option_027, optional_attr,
    "Config_option_028", H5T_STRING, eagle->config.Config_option_028, optional_attr,
    "Config_option_029", H5T_STRING, eagle->config.Config_option_029, optional_attr,
    "Config_option_030", H5T_STRING, eagle->config.Config_option_030, optional_attr,
    "Config_option_031", H5T_STRING, eagle->config.Config_option_031, optional_attr,
    "Config_option_032", H5T_STRING, eagle->config.Config_option_032, optional_attr,
    "Config_option_033", H5T_STRING, eagle->config.Config_option_033, optional_attr,
    "Config_option_034", H5T_STRING, eagle->config.Config_option_034, optional_attr,
    "Config_option_035", H5T_STRING, eagle->config.Config_option_035, optional_attr,
    "Config_option_036", H5T_STRING, eagle->config.Config_option_036, optional_attr,
    "Config_option_037", H5T_STRING, eagle->config.Config_option_037, optional_attr,
    "Config_option_038", H5T_STRING, eagle->config.Config_option_038, optional_attr,
    "Config_option_039", H5T_STRING, eagle->config.Config_option_039, optional_attr,
    "Config_option_040", H5T_STRING, eagle->config.Config_option_040, optional_attr,
    "Config_option_041", H5T_STRING, eagle->config.Config_option_041, optional_attr,
    "Config_option_042", H5T_STRING, eagle->config.Config_option_042, optional_attr,
    "Config_option_043", H5T_STRING, eagle->config.Config_option_043, optional_attr,
    "Config_option_044", H5T_STRING, eagle->config.Config_option_044, optional_attr,
    "Config_option_045", H5T_STRING, eagle->config.Config_option_045, optional_attr,
    "Config_option_046", H5T_STRING, eagle->config.Config_option_046, optional_attr,
    "Config_option_047", H5T_STRING, eagle->config.Config_option_047, optional_attr,
    "Config_option_048", H5T_STRING, eagle->config.Config_option_048, optional_attr,
    "Config_option_049", H5T_STRING, eagle->config.Config_option_049, optional_attr,
    "Config_option_050", H5T_STRING, eagle->config.Config_option_050, optional_attr,
    "Config_option_051", H5T_STRING, eagle->config.Config_option_051, optional_attr,
    "Config_option_052", H5T_STRING, eagle->config.Config_option_052, optional_attr,
    "Config_option_053", H5T_STRING, eagle->config.Config_option_053, optional_attr,
    "Config_option_054", H5T_STRING, eagle->config.Config_option_054, optional_attr,
    "Config_option_055", H5T_STRING, eagle->config.Config_option_055, optional_attr,
    "Config_option_056", H5T_STRING, eagle->config.Config_option_056, optional_attr,
    "Config_option_057", H5T_STRING, eagle->config.Config_option_057, optional_attr,
    "Config_option_058", H5T_STRING, eagle->config.Config_option_058, optional_attr,
    "Config_option_059", H5T_STRING, eagle->config.Config_option_059, optional_attr,
    "SVN_Version", H5T_STRING, eagle->config.SVN_Version, optional_attr,
    NULL);

  if(high5err == EXIT_FAILURE)
    status = EXIT_FAILURE;

  if(close_h5(file_id) == EXIT_FAILURE)
    return EXIT_FAILURE;

  return status;
}
